accordproject/models

src/cicero/contract.cto
src/cicero/runtime.cto

A contract can have a list (possibly an empty list!) of participants.
I use the composer concept `Participant` as a synonym for `party` in this context. The alternative would be to add a top `AccordParty` type that extends `Participant` and to replace all uses of Participant in this library with AccordParty.
I also add two base obligation types for logical payment and notification obligations to be emitted as events by contracts. These obligations should be handled and configured client-side to determine the channel (e.g. Email / Slack / Letter etc) for the fulfilment of the obligation.
Refer to https://hyperledger.github.io/composer/latest/reference/cto_language for description of the built-in participant and event types.

Add Contract Parties & Notices

---

src/cicero/dom.cto

This drills down in where logic might be inlined in the DOM model, separating between three kinds of logic:
- Declarations (e.g., functions at the beginning of the template which can be called)
- Parameter expressions (e.g., an interest rate should be a positive number)
- Element expressions (e.g., programmatically creates a bit of text, or a list in the contract etc.)

(fix) Adjust Ergo support in DOM model

---

views/model.njk

The generated TypeScript files are saved to the root of the build directory rather than inside the model directories. This PR updates the TypeScript link in the model view to point to the root directory.
Closes #30

Fix TypeScript download links

---

build.js
package-lock.json
package.json
src/finance/bond@0.2.0.cto
src/finance/loan@0.2.0.cto
src/money@0.2.0.cto
src/payment/endorsement@0.2.0.cto
src/time@0.2.0.cto
src/v2.0/time.cto

Updates to various models in accordance with the new versioning scheme (#15).
- `time@0.2.0` is a re-release of `v2/time.cto` to bring it into line with the new versioning scheme.
- `money@0.2.0` uses `DigitalMonetaryAmount` rather than `CrytoMonetaryAmount`
- `loan@0.2.0.cto` is fixed to address a typo. Fixes #34 .
- All models now use `time@0.2.0` and `money@0.2.0`

fix(various): Typo in loan, refactor crypto -> digital

---

views/index.njk

Signed-off-by: Peter Hunn <code@peterhunn.com>
- Fix grammatical typo
- Update links from Composter-Concerto to Concerto

fix(views): correct typo and update links

---

CONTRIBUTING.md

Signed-off-by: Arshad Kazmi <arshadkazmi42@gmail.com>
This PR fixes the broken link of code of conduct in CONTRIBUTING.md file
- Change the old code of conduct url (`https://github.com/accordproject/docs/blob/master/Accord%20Project%20Code%20of%20Conduct.pdf`) to new url (`https://lfprojects.org/policies/code-of-conduct/`)

fix(CONTRIBUTING): broken coc link - I70

---

CONTRIBUTING.md
README.md

Signed-off-by: Michael Zhou <myz227@nyu.edu>
<OVERALL SUMMARY OF PULL REQUEST>
Updated markdown files by correcting for incorrect markdown links, integrating existing links into new markdown, and ensuring consistency in markdown style. Also fixes typos, grammar, and punctuation errors in documentation. Some tests failed due to code vulnerabilities.
- Modified markdown to be more appropriate with content of associated links
- Fixed typos and miscellaneous errors in punctuation and grammar
- [Cicero Template Library Issue 257](https://github.com/accordproject/cicero-template-library/issues/257)
- Pull Request [#280](https://github.com/accordproject/cicero-template-library/pull/280)

docs(*): update markdown files and fix typos - I257

---

src/markdown/ciceromark.cto
src/markdown/commonmark.cto

Publish the latest versions for the CommonMark and CiceroMark models used in https://github.com/accordproject/markdown-transform
- Publish CiceroMark model
- Update CommonMark model
- Rename `commonmark/markdown.cto` to `markdown/commonmark.cto` (See #51)

fix(markdown) Update and rename CommonMark and CiceroMark models (#51)

---

src/cicero/runtime.cto

This is reverting a wrong update to `runtime.cto` which should still use the older `money.cto`. That change should be done as a new version for the runtime model.

fix(runtime) revert critical change to runtime CTO

---

src/ergo/altbase.cto
src/markdown/ciceromark.cto

- Add `ConditionalVariable` node to CiceroMark (See https://github.com/accordproject/markdown-transform/issues/130)
- Also documents the alternative base model used by the Ergo type checker (See https://github.com/accordproject/ergo/issues/698)

Models: Conditional Variables in Cicero Mark + Ergo Base

---

src/markdown/ciceromark@0.2.0.cto

This adds information to Conditional Variables in CiceroMark, in order to keep track of the alternative text.
- Add `whenTrue` and `whenFalse` fields to `ConditionalVariable` in CiceroMark
Change to support conditional variables in the Cicero UI. See:
- https://github.com/accordproject/cicero-ui/issues/233 and
- https://github.com/accordproject/markdown-transform/issues/162

feature(CiceroMark) Add whenFalse/whenTrue to Conditional Variables

---

src/markdown/ciceromark.cto
src/markdown/ciceromark@0.2.0.cto

fix(wrong) correctly fixes CiceroMark 2.0 rather than the old version

---

build.js
package-lock.json
package.json
src/markdown/ciceromark@0.3.1.cto
src/markdown/templatemark@0.1.1.cto

Signed-off-by: Dan Selman <danscode@selman.org>
- Update to latest concerto-tools, which includes improved JSON Schema generation
- Use qualified import so that XML Schema generation doesn't fail

fix(json-schema) : update concerto-tools to fix issues with json schema gen

---

src/accordproject/runtime.cto
src/markdown/ciceromark@0.3.1.cto
src/markdown/templatemark@0.1.1.cto
src/signature/block@0.2.0.cto

- Revert some imports from temporary `cicero-1.0` published branch to official published models

chore(publish) Switch import back to published models.accordproject.org [Step 1]

---

src/accordproject/obligation.cto
src/docusign/connect@0.3.0.cto
src/payment/payment@0.2.0.cto
src/signature/signature@0.2.0.cto

- Revert remaining imports from temporary `cicero-1.0` published branch to official published models

chore(publish) Switch import back to published models.accordproject.org [Step 2]

---

src/usa/state@0.2.0.cto

- Rename `State` to `USState` in `usr/state` model -- avoiding collision with Accord Project contract state
- It's not great, but we don't have a good name resolution in Concerto the same way we do in Ergo

fix(usa) Rename State -> USState to avoid name collisions

---

src/accordproject/runtime.cto

- Some templates use obligations without Accord Project parties, so reverting this change to the base models
- This may point to an even simpler base model where we do not specify any AP party class at all, but allow Participants. This will need to be discussed

feature(base) Revert Obligation change, back to Participants

---

src/accordproject/party.cto
src/accordproject/runtime.cto
src/signature/block@0.2.0.cto

Handling of contract parties in the base models is inconsistent.
While we bake in a notion accord project party for contracts: https://github.com/accordproject/models/blob/2051f2724546d58a9b06c3b62599de9aa9b24fb8/src/accordproject/contract.cto#L24-L27
we do not require obligations to be tied to those parties at runtime:
https://github.com/accordproject/models/blob/2051f2724546d58a9b06c3b62599de9aa9b24fb8/src/accordproject/runtime.cto#L40-L44
The reason for the latter is clearer in retrospect: we sometimes need contracts tied to other kinds of parties that could be identified by something different from a `partyId`. E.g., a business's email in this template: https://github.com/accordproject/cicero-template-library/blob/d0f6e14be765da258c180 …

feature(base) Simplify parties in Accord Project models

---

src/concerto/metamodel@0.2.0.cto

- Add new version of meta model, consistent with https://github.com/accordproject/web-components/pull/353
- New model adds:
- 🐛 Fix to class declarations so they include fields!
- 🆕 decorators to drive the new form-based editor
- 🆕 regex checks on some of the names
- Additional changes:
- Rename class name field from `identifier` to `name`
- Refactored import classes to more easily distinguish between `namespace.Type` and `namespace.*`
- Add distinction between `Identified` and `IdentifiedBy` consistent with Concerto 1.0
- Made type references local names rather than fully qualified names

feature(concerto) Add new version of metamodel

---

build.js
concertoVersions.js
src/cicero/dom.cto
styles.css
views/model.njk

Adds a button to download the JSON syntax tree for the model, based on the Concerto metamodel.
- Add JSON AST export button
- Add some `alt` fields to the export buttons
- Some button re-ordering

feature(metamodel) Add link to download JSON syntax tree based on Concerto metamodel

---

package-lock.json
package.json
src/concerto/metamodel@0.2.0.cto

- Upgrade Concerto to `1.1.2` including bug fixes to the metamodel support
- Update the Concerto Metamodel v2 to include type references as possible decorator arguments

fix(metamodel) Update needed for bug fixes in Concerto 1.1.2

---

build.js
package-lock.json
package.json
views/model.njk

- Updated to latest Concerto `1.1.3`
- Uses the new Typescript visitor to generate a zip file with Typescript interfaces and classes
- <ONE>
- <TWO>
- Issue #<NUMBER>
- Pull Request #<NUMBER>

chore(concerto) : update concerto version and use new Typescript generator

---

src/concerto/metamodel@0.3.0.cto

This PR includes a new version `0.3` for the Concerto MetaModel, with improvements to the structure and terminology.
- Rename `field` to `property` throughout the metamodel
- Remove the abstract ClassDeclaration, using ConceptDeclaration as the top-most type for concept/asset/transaction/even/participants
- Some corresponding cleanups to default values
- Some corresponding cleanups to the top level properties, using `enums` and `concepts` for clarity in the instances
- This is a non-backward compatible change
- This should be tested in Concerto itself and in the Model Builder in Web components

feature(concerto) Add version 0.3 of Concerto metamodel

---

src/concerto/metamodel@0.3.0.cto

This PR makes adjustments to the Concerto Metamodel 0.3 so it can be used to redesign the Concerto parser ahead of version `2.0`.
- Adds optional file location data for declarations and properties
- Adds an optional Concerto version field which indicates which version of Concerto the model supports
- Factors out common part of declarations (`name` `decorators` and `location`). Note that this change means decorators can now be placedon enums.

fix(metamodel) Fixes to metamodel 0.3 for Concerto 2.0

---

src/concerto/metamodel@0.3.0.cto

If models are resolved from URI during import it could be nice to keep track of which model comes from where.
- Adds an optional `sourceUri` to the `Model` class in the metamodel

feature(metamodel) Add optional source URI for models
