accordproject/models

src/cicero/runtime.cto

(fix) Allow default empty request/response to be instantiated

---

build.js

Signed-off-by: Matt Roberts <code@rbrts.uk>

Fix mixed content warnings

---

src/ergo/monitor.cto

Model for the output of the Ergo compiler monitor

---

src/finance/loan.cto

Third time is a charm! 
I have revised to contain just the loan model. My intent is to make this compatible with HL Composer. This is my first try at DLT development. Apologies in advance if I am completely lost on some of the core concepts.
Regarding the cicero contract and clauses, it seems like that should be drafted or reviewed by a lawyer rather than a developer. Do lawyers do that here or is there a more appropriate forum for contract review?

Peer review for org.accordproject.finance.loan

---

src/docusign/connect.cto

Signed-off-by: Diana Lease <dianarlease@gmail.com>

extend ds connect model

---

README.md
views/page.njk

(fix) Add legal disclaimer

---

build.js
package-lock.json
package.json

(chore) Bump to Concerto 0.70

---

package-lock.json
package.json

(chore) Bump Concerto 0.70.5

---

README.md
package-lock.json
package.json

chore(dep) Switch to Concerto 0.71

---

CHARTER.md
README.md

- Initiate Linux Foundation charter as a markdown file.
- N/A
- N/A

docs(CHARTER): implement linux foundation charter - I40

---

README.md

Signed-off-by: Peter Hunn <code@peterhunn.com>

Update Concerto reference

---

src/binary.cto
src/docusign/connect@0.2.0.cto

- Includes a new CTO model for binary objects or references to binary objects
- Uses those to model DocuSign attachments

Models for binary resource and DocuSign attachments

---

build.js
package-lock.json
package.json
src/docusign/connect@0.2.0.cto

This PR includes:
- Bug fix in DocuSign Connect model 0.2.0 (wrong import)
- Switch to Accord Project's Concerto 0.80.0
- Build log includes version of model for easier debugging

Build & Docusign

---

README.md

Signed-off-by: DEBSUBHRO <debsubhro.roy10@yahoo.com>
<OVERALL SUMMARY OF PULL REQUEST>
**Changes**
- Centering the title 
- Centering the badges
**Related Issues**
* Issue #79
* Pull Request #60

docs(README): center ap logo and title

---

README.md

- added license badge
- added slack badge
- None
- accordproject/techdocs/issues/82

docs(README): add license and slack badges

---

DEVELOPERS.md
README.md

Signed-off-by: vaibhav111tandon <vaibhav.tandongcet@gmail.com>
- Added a link for DEVELOPERS.md from techdocs
- Issue #57

docs(DEVELOPERS): init file - I57

---

README.md

Signed-off-by: Aayush Bisen <aayush23101998@outlook.com>
Updated the Slack badge to "Accord Project - Join Slack" in README.
- Updated the Slack badge in README.
- None
- https://github.com/accordproject/techdocs/issues/78

docs(README): update slack badge

---

src/markdown/ciceromark.cto

Remove obsolete clauseText field

---

src/ergo/options.cto

model(ergo) Add CTO for Ergo compiler options

---

src/ergo/options.cto

fix(ergo) Clean up Ergo options model

---

README.md

<OVERALL SUMMARY OF PULL REQUEST>
- Fix readme typo
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>

fix(README): typo - I88

---

src/markdown/ciceromark.cto

feature(CiceroMark) Add variable list node

---

src/finance/loan.cto
src/finance/loan@0.2.0.cto
src/markdown/ciceromark.cto

Signed-off-by: Dan Selman <danscode@selman.org>
- Fix issues with XMLSchema generation for loan models that `import *`
- DRY-up the Variables in the ciceromark model

(fix) clean up models

---

src/creative/creativeWork.cto

Small CTO illustrating creative works modeling

---

src/markdown/ciceromark.cto

fix(ciceromark) Add missing format attribute on variables

---

src/money@0.2.0.cto

Signed-off-by: niallroche niall.roche@gmail.com
Adding a concept to store data about currency conversion. The value can be computed from currency rates supplied by an oracle.
- added a new concept CurrencyConversion
- Pull Request #357

feat(models): add new CurrencyConversion concept

---

src/signature/block.cto

- Updated decorators to use name/value syntax
- Created a new namespace for signature block

Namespace for signature blocks

---

src/timezone.cto

Add a model with IANA timezone names

feat(timezone) : add tz names

---

build.js
package-lock.json
package.json
src/cicero/runtime@0.2.0.cto
src/docusign/connect.cto
src/docusign/connect@0.3.0.cto
src/payment/payment.cto
src/payment/payment@0.2.0.cto
src/signature/signature@0.2.0.cto

Upgrades the build script and models to support Concerto v1.
- New model files for those that depend on `org.accordproject.cicero.runtime`
- Added support for reading a compatibility comment within the model file `// requires: concerto-core:>= 1.0.0-20210215133932` to control whether the model file gets processed or not, based on the version of `concerto-core` listed in package.json

feat(concerto v1) : update

---

_redirects
build.js

- Added `_redirects` file in root folder<ONE>
- Added a command to copy the same file to publish directory<TWO>

feat(netlify): added `_redirects` file to handle time model outdated link

---

package-lock.json
package.json

- Upgrade to latest Concerto `1.0.0-alpha.6`

chore(dep) Upgrade Concerto to 1.0.0-alpha6

---

package-lock.json
package.json
src/accordproject/contract.cto
src/accordproject/obligation.cto
src/accordproject/party.cto
src/accordproject/runtime.cto
src/docusign/connect@0.3.0.cto
src/payment/payment@0.2.0.cto
src/signature/block@0.2.0.cto
src/signature/signature@0.2.0.cto

- Switch to Concerto `1.0.0`
- Cleans up models

chore(release) Switch to published Concerto 1.0.0

---

package-lock.json
package.json

- Upgrade to latest Concerto `1.0.2` which includes dependencies upgrades, addressing security vulnerabilities

chore(dep) Upgrade to Concerto 1.0.2

---

src/markdown/ciceromark@0.3.2.cto
src/markdown/templatemark@0.1.2.cto

- New markdown document models using the latest Concerto metamodel (for decorators)

feature(markdown) Markdown models using the new Concerto metamodel

---

build.js
package-lock.json
package.json
views/model.njk

Signed-off-by: Dan Selman <danscode@selman.org>
- Updates to Concerto v1.2.1
- Adds CSharp code generation

feat(csharp) : update concerto and add csharp gen

---

src/concerto/decorators.cto

Signed-off-by: Dan Selman <danscode@selman.org>
- Defines a model that allows sets of decorators to be declaratively added to an existing Concerto model

feat: declarative application of decorators

---

src/markdown/commonmark@0.4.0.cto

Signed-off-by: TC5022 <tanyac5022002@gmail.com>
- <ONE> This is a PR to introduce table extensions in the common mark and ciceromark models
- <TWO> This is required to complete the table transformations in other markdown formats

feat(markdown-models): add support for tables

---

src/concerto/metamodel@1.0.0.cto

Updates  `metamodel@1.0.0` with `MapType` and `StringLengthValidator`.
- <ONE> adds MapType
- <TWO> adds StringLengthValidator

feat(metamodel): update metamodel with MapType and StringLengthValidator

---

src/markdown/templatemark@0.5.0.cto

Adds TemplateMark v0.5.0
- Updates the JoinDefinition to support localised formatting of lists
- <ONE>
- <TWO>
- Issue #<NUMBER>
- Pull Request #<NUMBER>

feat(join) : add list formatting options

---

README.md

updatted slack links to discord links
reference to https://github.com/accordproject/techdocs/issues/388
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- Issue #<NUMBER>
- Pull Request #<NUMBER>

docs(readme): updated slack to discord in Readme

---

src/contact@1.0.0.cto

Adds standard definitions for Email Address and Phone Number
- Definitions in this file do not enforce character constraints (for example, using regular expressions or digits). It is the responsibility of the application to enforce these constraints. This allows broader compatibility between systems and agreements which may have different requirements.

feat(contact): add EmailAddress and PhoneNumber
